classdef TestAgeOnlyRulBaseline < matlab.unittest.TestCase
    methods (Test)
        function predictsHeldoutRulFromTrainingLifetimesOnly(testCase)
            features = table( ...
                ["TrainA"; "TrainA"; "TrainA"; "HeldB"; "HeldB"; "HeldB"; "HeldB"; "HeldB"], ...
                [1; 1; 1; 1; 1; 1; 1; 1], ...
                ["outer race"; "outer race"; "outer race"; "outer race"; "outer race"; "outer race"; "outer race"; "outer race"], ...
                [1; 2; 3; 1; 2; 3; 4; 5], ...
                [0; 1; 2; 0; 1; 2; 3; 4], ...
                VariableNames=["BearingID", "ConditionID", "FailureLabel", "SnapshotIndex", "ElapsedMinutes"]);
            folds = table( ...
                [1; 1], ...
                ["nested leave-one-bearing-out pilot"; "nested leave-one-bearing-out pilot"], ...
                ["TrainA"; "HeldB"], ...
                ["train"; "heldout"], ...
                VariableNames=["FoldID", "Protocol", "BearingID", "Role"]);

            predictions = evaluateAgeOnlyRulBaseline(features, folds);

            testCase.verifyEqual(height(predictions), 5);
            testCase.verifyEqual(predictions.BearingID, repmat("HeldB", 5, 1));
            testCase.verifyEqual(predictions.ActualRULMinutes', [4 3 2 1 0]);
            testCase.verifyEqual(predictions.PredictedRULMinutes', [2 1 0 0 0]);
            testCase.verifyEqual(predictions.AbsoluteErrorMinutes', [2 2 2 1 0]);
            testCase.verifyEqual(predictions.NormalizedAbsoluteError', [0.4 0.4 0.4 0.2 0], AbsTol=1e-12);
        end

        function usesMedianTrainingRemainingLife(testCase)
            features = table( ...
                ["TrainA"; "TrainA"; "TrainA"; "TrainC"; "TrainC"; "TrainC"; "TrainC"; "TrainC"; "HeldB"; "HeldB"], ...
                ones(10, 1), ...
                repmat("outer race", 10, 1), ...
                [1; 2; 3; 1; 2; 3; 4; 5; 1; 2], ...
                [0; 1; 2; 0; 1; 2; 3; 4; 0; 1], ...
                VariableNames=["BearingID", "ConditionID", "FailureLabel", "SnapshotIndex", "ElapsedMinutes"]);
            folds = table( ...
                [1; 1; 1], ...
                repmat("nested leave-one-bearing-out pilot", 3, 1), ...
                ["TrainA"; "TrainC"; "HeldB"], ...
                ["train"; "train"; "heldout"], ...
                VariableNames=["FoldID", "Protocol", "BearingID", "Role"]);

            predictions = evaluateAgeOnlyRulBaseline(features, folds);

            testCase.verifyEqual(predictions.PredictedRULMinutes', [3 2]);
        end
    end
end
